import type { Event } from "@/types/event";
import type { Artist } from "@/types/artist";
import type { User } from "@/types/user";

export const mockUser: User = {
  id: "usr_01",
  name: "Alex",
  lastName: "Rivas",
  email: "alex@orbit.local",
  role: "AGENCY",
  organizationId: "org_orbit",
};

export const mockEvents: Event[] = [
  {
    id: "evt_001",
    title: "Warehouse Session",
    eventDate: "2026-07-04",
    startTime: "22:00",
    endTime: "04:00",
    venueName: "Galpao Aurora",
    address: "Rua das Luzes, 480",
    city: "Sao Paulo",
    state: "SP",
    notes: "Line-up com foco em house progressivo e set visual.",
    artistId: "art_001",
    clientId: "cli_001",
    clientName: "Mariana Silva",
    clientPhone: "11999990000",
    clientEmail: "mariana@cliente.local",
    organizationId: "org_orbit",
  },
  {
    id: "evt_002",
    title: "Sunset Private",
    eventDate: "2026-07-12",
    startTime: "16:30",
    endTime: "23:00",
    venueName: "Casa Mirante",
    address: "Av. Alto da Serra, 90",
    city: "Campinas",
    state: "SP",
    notes: "Evento intimista para marca de moda.",
    artistId: "art_002",
    clientId: "cli_002",
    clientName: "Nox Studio",
    clientPhone: "11988887777",
    clientEmail: "events@nox.local",
    organizationId: "org_orbit",
  },
  {
    id: "evt_003",
    title: "Neon Lobby",
    eventDate: "2026-08-02",
    startTime: "20:00",
    endTime: "02:00",
    venueName: "Hotel Nox",
    address: "Rua Prata, 144",
    city: "Rio de Janeiro",
    state: "RJ",
    notes: "Recepcao premium com DJ residente e after controlado.",
    artistId: "art_003",
    clientId: "cli_003",
    clientName: "Hotel Nox",
    clientPhone: "21977776666",
    clientEmail: "booking@hotelnox.local",
    organizationId: "org_orbit",
  },
];

export const mockArtists: Artist[] = [
  {
    id: "art_001",
    name: "DJ",
    lastName: "Gabriel",
    email: "gabriel@orbit.local",
    phone: "11999991111",
    role: "ARTIST",
    organizationId: "org_orbit",
  },
  {
    id: "art_002",
    name: "Lia",
    lastName: "Moraes",
    email: "lia@orbit.local",
    phone: "11988882222",
    role: "ARTIST",
    organizationId: "org_orbit",
  },
  {
    id: "art_003",
    name: "Rafa",
    lastName: "Nox",
    email: "rafa@orbit.local",
    phone: null,
    role: "ARTIST",
    organizationId: "org_orbit",
  },
];
